// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryProject.DataAccess.DataContextModels;

public partial class Module
{
    public int Id { get; set; }

    public string ModuleName { get; set; }

    public string ModuleCode { get; set; }

    public virtual ICollection<UserModuleAccess> UserModuleAccesses { get; set; } = new List<UserModuleAccess>();
}