// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryProject.DataAccess.DataContextModels;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Qty { get; set; }

    public decimal Price { get; set; }

    public DateTime DateCreated { get; set; }

    public int CreatedById { get; set; }

    public DateTime? DateModified { get; set; }

    public int? ModifiedById { get; set; }

    public virtual ICollection<ProductAdjustment> ProductAdjustments { get; set; } = new List<ProductAdjustment>();

    public virtual ICollection<SalesDetail> SalesDetails { get; set; } = new List<SalesDetail>();
}