// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryProject.DataAccess.DataContextModels;

public partial class ProductAdjustment
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string Action { get; set; }

    public int? Quantity { get; set; }

    public int? SalesDetailId { get; set; }

    public DateTime DateCreated { get; set; }

    public int CreatedById { get; set; }

    public DateTime? DateModified { get; set; }

    public int? ModifiedById { get; set; }

    public virtual Product Product { get; set; }

    public virtual SalesDetail SalesDetail { get; set; }
}